version: '3.8' # Specify the version to avoid validation issues

services:
  web:
    image: nginx:latest
    ports:
      - "81:81"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    build:
      dockerfile: ./php/Dockerfile
    volumes:
      - ./app:/app
    environment:
      - DB_HOST=db
      - DB_NAME=slimdb
      - DB_USER=root
      - DB_PASS=root
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: slimdb
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: